article/urls.py
from django.contrib import admin
from django.urls import path
from . import views as article_views

app_name = 'article_urls'

urlpatterns = [
  path('', article_views.articles, name='articles'),
  path('article/comment/<int:id>/', article_views.comment, name='comment'),
  path('article/add/', article_views.add, name='article_add'),
  path('article/<int:id>/', article_views.detail, name='article_detail'),
  path('article/<int:id>/visibility/', article_views.article_visibility, name='article_visibility'),
  path('article/<int:id>/delete/', article_views.delete, name='article_delete'), 
  path('article/<int:id>/update/', article_views.update, name='article_update'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from article import views as article_views
from django.conf import settings
from django.conf.urls.static import static
from user import views as user_views

urlpatterns = [
    # admin
    path('admin/', admin.site.urls, name='admin'),
    path('settings/', user_views.user_settings, name='settings'),

    # paths
    path('', article_views.index, name='index'),
    path('about/', article_views.about, name='about'),

    path('register/', user_views.register, name='register'),
    path('login/', user_views.user_login, name='login'),

    # search
    path('search/', user_views.search, name='search'),
    path('search/<str:query>', user_views.search, name='search'),

    # includes
    path('articles/',include('article.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views as user_views

app_name = 'user_urls'

urlpatterns = [
  path('dashboard/', user_views.dashboard, name='dashboard'),

  path('logout/', user_views.user_logout, name='logout'),

  path('<int:id>/', user_views.user_profile, name='profile'),
  path('<str:username>/', user_views.user_profile, name='profile'),
  
  path('<str:username>/', user_views.user_profile, name='username_profile'),
  path('<str:username>/articles/', user_views.user_articles, name='articles'),
]

templates/includes/navbar.html
<header class="p-2">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <!-- Site Navigation -->
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li>
          <a href="{% url 'index' %}" class="navbar-brand px-2">
          Home
          </a>
        </li>
        <li>
          <a href="{% url 'about' %}" class="navbar-brand px-2">
          About
          </a>
        </li>
        <li>
          <a href="{% url 'article_urls:articles' %}" class="navbar-brand px-2">
            Articles
          </a>
        </li>
      </ul>
      <!-- Search form -->
      <form  class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" action="{% url 'search' %}">
        {% csrf_token %}
        <input type="search" name="q" class="form-control" placeholder="Search..." aria-label="Search">
      </form>
      <!-- User Profile -->
      <div class="text-end">
        {% if request.user.is_authenticated %}
          <div class="btn-group">
            <a href="{% url 'user_urls:profile' 'me' %}" class="btn">
              {{ request.user.username }}
            </a>
            <button type="button" class="btn dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown">
            </button>
            <div class="dropdown">
              <ul class="dropdown-menu">
                <li><a href="{% url 'user_urls:profile' 'me' %}" class="dropdown-item">Profile</a></li>
                <li><a href="{% url 'user_urls:dashboard' %}" class="dropdown-item">Dashboard</a></li>
                <li><hr class="dropdown-divider"></li>
                <h6 class="dropdown-header">Article</h6>
                <li><a href="{% url 'user_urls:articles' request.user.username %}" class="dropdown-item">My Articles</a></li>
                <li><a href="{% url 'article_urls:article_add' %}" class="dropdown-item">Article Add</a></li>
                <li><hr class="dropdown-divider"></li>
                <td><a href="{% url 'settings' %}" class="dropdown-item">Settings</a></td>
                <li><a href="{% url 'user_urls:logout' %}" class="dropdown-item text-danger">Logout</a></li>   
              </ul>
            </div>
          </div>
        {% else %}
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'login' %}" class="nav-link px-2 link-light">Login</a></li>
            <li><a href="{% url 'register' %}" class="nav-link px-2 link-light">Register</a></li>
          </ul>
        {% endif %}
      </div>
    </div>
</header>