article/urls.py
from django.contrib import admin
from django.urls import path
from . import views as article_views

app_name = 'article_urls'

urlpatterns = [
  path('', article_views.articles, name='articles'),
  path('article/comment/<int:id>/', article_views.comment, name='comment'),
  path('article/add/', article_views.add, name='article_add'),
  path('article/<int:id>/', article_views.detail, name='article_detail'),
  path('article/<int:id>/visibility/', article_views.article_visibility, name='article_visibility'),
  path('article/<int:id>/delete/', article_views.delete, name='article_delete'), 
  path('article/<int:id>/update/', article_views.update, name='article_update'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from article import views as article_views
from django.conf import settings
from django.conf.urls.static import static
from user import views as user_views

urlpatterns = [
    # admin
    path('admin/', admin.site.urls, name='admin'),
    path('settings/', user_views.user_settings, name='settings'),

    # paths
    path('', article_views.index, name='index'),
    path('about/', article_views.about, name='about'),

    path('register/', user_views.register, name='register'),
    path('login/', user_views.user_login, name='login'),

    # search
    path('search/', user_views.search, name='search'),
    path('search/<str:query>', user_views.search, name='search'),

    # includes
    path('articles/',include('article.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views as user_views

app_name = 'user_urls'

urlpatterns = [
  path('dashboard/', user_views.dashboard, name='dashboard'),

  path('logout/', user_views.user_logout, name='logout'),

  path('<int:id>/', user_views.user_profile, name='profile'),
  path('<str:username>/', user_views.user_profile, name='profile'),
  
  path('<str:username>/', user_views.user_profile, name='username_profile'),
  path('<str:username>/articles/', user_views.user_articles, name='articles'),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Article(models.Model):
  author = models.ForeignKey(
    'auth.User',
    on_delete=models.CASCADE,
    verbose_name='Author'
    ) # if user is deleted, delete the article
  
  created_at = models.DateTimeField(
    auto_now_add=True, # when the article is created, set the date and time 
    verbose_name='Created At'
    )

  title = models.CharField(
    max_length=50,
    verbose_name='Title'
    ) # max length of 50 characters
  content = RichTextField(
    verbose_name='Content'
    ) # no max length

  article_image = models.FileField(
    blank=True,
    null=True,
    verbose_name='Article Image'
    )

  visibility = models.BooleanField(
    default=True,
    verbose_name='Article Visibility'
    )

  def __str__(self):
    return f'{self.author} - {self.title}'
  
  class Meta:
    ordering = ['-created_at'] # order by created_at descending
  
class Comment(models.Model):
  article = models.ForeignKey(
    Article,
    on_delete=models.CASCADE,
    verbose_name='Article',
    related_name='comments' # to access comments from article object
    )
  comment_author = models.CharField(
    'auth.User',
    max_length=50,
    )
  comment_content = models.CharField(
    max_length=200,
    verbose_name='Comment'
    )
  comment_date = models.DateTimeField(
    auto_now_add=True,
    verbose_name='Comment Date'
    )
  
  def __str__(self):
    return self.comment_content
  
  class Meta:
    ordering = ['-comment_date'] # order by created_at descending

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
  class Meta:
    model = Article
    fields = [
      'title',
      'content',
      'article_image',
      'visibility']

article/views.py
from django.shortcuts import (
  render,
  redirect,
  get_object_or_404
)
from django.contrib import messages

from .models import Article, Comment
from .forms import ArticleForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
  return render(request, 'index.html')

def about(request):
  return render(request, 'about.html')

def articles(request):
  # descending: -created_at, ascending: created_at
  articles = Article.objects.all().order_by('-created_at')

  visible_articles = articles.filter(visibility=True).all()

  context = {
    'articles': visible_articles
  }
  return render(request, 'articles.html', context)

def detail(request, id):
  referer = request.META.get('HTTP_REFERER') # get the previous page url

  try:
    # try to get the article with the given id
    article = Article.objects.get(id=id)
  except Article.DoesNotExist:
    # if not found, show an error message and redirect
    messages.error(request, f'Article not found with id {id}')
    return redirect(referer or 'index')
  
  if not article.visibility:
    if not request.user.is_authenticated or request.user != article.author:
      messages.error(request, 'Article is not visible')
      return redirect(referer or 'index')

  context = {
    'article': article,
    'comments': article.comments.all() # related_name
    }

  return render(request, 'article/article_detail.html', context)

@login_required(login_url='login')
def add(request):
  form = ArticleForm(
    request.POST or None,
    request.FILES or None
    )

  if form.is_valid():
    # commit=False means don't save to database yet
    article = form.save(commit=False)
    # set the author to the current user
    article.author = request.user
    article.save()
    messages.success(request, 'Article has been added')
    return redirect('index')

  return render(request, 'article/article_add.html', {'form': form})

@login_required(login_url='login')
def delete(request, id):
  article = get_object_or_404(Article, id=id)
  article.delete()
  messages.success(
    request,
    'Article has been deleted')

  referer = request.META.get('HTTP_REFERER')
  return redirect(referer or 'index')

@login_required(login_url='login')
def update(request, id):
  article = get_object_or_404(Article, id=id)

  form = ArticleForm(
    request.POST or None,
    request.FILES or None,
    instance=article
  )
  
  if form.is_valid():
    # commit=False means don't save to database yet
    article = form.save(commit=False)
    article.author = request.user
    article.save()
    messages.success(request, 'Article has been updated')
    return redirect('article_urls:article_detail', id=id)
  
  return render(request, 'article/article_update.html', {'form': form})

@login_required(login_url='login')
def article_visibility(request, id):
  article = get_object_or_404(Article, id=id)
  article.visibility = not article.visibility
  article.save()
  messages.success(
    request,
    f'Article visibility has been changed to {article.visibility}'
  )

  referer = request.META.get('HTTP_REFERER')
  return redirect(referer or 'index')

def comment(request, id):
  article = get_object_or_404(Article, id=id)

  if request.method == 'POST':
    content = request.POST.get('comment_content')

    new_comment = Comment(
      article=article,
      comment_author=request.user,
      comment_content=content
    )
    new_comment.save()
    messages.success(request, 'Comment has been added')
  return redirect('article_urls:article_detail', id=id)

templates/article/article_add.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block body %}
  {% if form %}
    <div class="row">
      <div class="col-md-6 offset-md-3">
          <div class="lead">Add Article</div>
          <hr>
          <!-- Login form -->
          <form method="post">
              {% csrf_token %}
              {{ form.media }}
              {{ form|crispy }}
              <button type="submit" class="btn btn-secondary">Add</button>
          </form>
      </div>
    </div>
  {% else %}
    <div class="lead">
      A form for article has not yet been set up.
    </div>
  {% endif %}

{% endblock %}

templates/article/article_detail.html
{% extends "layout.html" %}

{% block body %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="display-4 text-center mb-3">{{ article.title }} </div>
    <div class="card border-0">
      <div class="card-header ">
        <div class="text-muted">
          <a href="{% url 'user_urls:profile' article.author.id %}" class="text-decoration-none">
            @{{ article.author.username }} 
          </a>
        </div>
      </div>
      <div class="card-body border">
        <div class="card-text">{{ article.content }}</div>
      </div>
      <div class="card-footer text-muted">
        {{ article.created_at }}
    </div>
  </div>
</div>  
<div class="col-md-6 offset-md-3">
  <!-- Comments -->
  <hr class="my-4">
  <div class="lead lead mt-3 mb-3">Comments</div>
    <!-- Comment List -->
    {% if comments %}
      {% for comment in comments %}
      <div class="card mb-3">
        <div class="card-body">
          <div class="text-muted">
            <a href="{% url 'user_urls:profile' comment.comment_author %}">
              @{{ comment.comment_author }}
            </a>
            {{ comment.comment_date }}
          </div>
          <div class="card-text">{{ comment.comment_content }}</div>
        </div>
      </div>
      {% endfor %}
    {% else %}
      <div class="card mb-3">
        <div class="card-body">
          <div class="card-text">No comments yet.</div>
        </div>
      </div>
    {% endif %}
  <!-- Comment Form -->
    {% if user.is_authenticated %}
    <form action="{% url 'article_urls:comment' article.id %}" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <textarea name="comment_content" class="form-control" placeholder="Comment" rows="3"></textarea>
        <button type="submit" class="btn btn-secondary mt-3">Send</button>
      </div>
    </form>
    {% endif %}
</div>

{% endblock %}

templates/article/article_update.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row">
  <div class="col-md-6 offset-md-3">
      <div class="lead">Edit Article</div>
      <hr>
      <!-- Login form -->
      <form method="post">
          {% csrf_token %}
          {{ form.media }}
          {{ form|crispy }}
          <button type="submit" class="btn btn-secondary">
              Update
          </button>
      </form>
  </div>
</div>
{% endblock %}